# tests/test_posts.py

def test_create_post(authorized_client):
    post_data = {
        "title": "My first automated post!",
        "content": "This was generated by Pytest.",
        "published": True
    }

    res = authorized_client.post("/posts", json=post_data)

    assert res.status_code == 201

    created_post = res.json()
    assert created_post["title"] == "My first automated post!"
    assert created_post["content"] == "This was generated by Pytest."
    assert created_post["published"]
    assert "owner_id" in created_post


def test_unauthorized_user_create_post(client):
    post_data = {
        "title": "Hacker Post",
        "content": "I shouldn't be allowed to post this."
    }

    res = client.post("/posts", json=post_data)
    assert res.status_code == 401


1
