"""removed rating columns formt the post table

Revision ID: bc5ffa927142
Revises: 216844e71a7a
Create Date: 2026-04-17 17:19:22.974027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5ffa927142'
down_revision: Union[str, Sequence[str], None] = '216844e71a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ratings', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
